# -*- coding: utf-8 -*-
"""Create a List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-PVfYUnVvMHftGV019KUBmQe5Zr8ieL
"""

# A foreign function library used to create C compatible data types in python
import ctypes

class MeraList:

  def _init_(self):
    self.size = 1
    self.n = 0
    # create a C type array with size = self.size
    self.A = self._make_array(self.size)

def _make_array(self,capacity):
    #This code creates a C type array(static,referential)with size capacity
    return (capacity*ctypes.py_object)()

L = MeraList()

type(L)

print(L)

