# -*- coding: utf-8 -*-
"""Dynamic arrays.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-PVfYUnVvMHftGV019KUBmQe5Zr8ieL
"""

import sys

L=[]

for i in range(100):
  print(i, sys.getsizeof(L))
  L.append(i)

